apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "readaloud.fullname" . }}-config
  labels:
    {{- include "readaloud.labels" . | nindent 4 }}
data:
  UPLOAD_DIR: /data/uploads
  POSTGRES_HOST: {{ include "readaloud.postgresHost" . | quote }}
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
